### PR TITLE
SourceGenerator Version

### LINKED ISSUE #1: Consider adding source generator version
Because locks are usually part of the implementation details and not part of the public API, it would be nice to be able to use this polyfill without bothering the consumers of our libraries with an extra transitive dependency. To that extend I think it would be a nice addition to provide a seperate roslyn source generator package that emits the `Lock` code into the consumers code base as internal classes. This way the code is essentially copied into the consuming libraries code base during compilation and does not create that extra transitive dependency.

Of course this comes with a downside: because the `Lock` type is now internal for anything before `.NET9`, we can't take or return any `Lock` objects in our public API. But as mentioned before, for most cases this doesn't happy anyway.

My proposal would be to make a second project (e.g. `Backport.System.Threading.Lock.SourceGenerator`) in the solution which emits the `Lock` and `LockFactory` code, which can be configured through the `.csproj` to emit the code either as `public` or `internal`. The default should probably be `internal`. The `Backport.System.Threading.Lock` project can add a compile-time reference to `Backport.System.Threading.Lock.SourceGenerator` and configure it to emit the code as `public`. The `Lock` and `LockFactory` code can then be removed from `Backport.System.Threading.Lock` so that the code only lives in a single space.

This would result in 2 packages:
- `Backport.System.Threading.Lock`: exactly the same package it is now (but compiled slightly differently). A runtime dependency with a `public` `Lock` class.
- `Backport.System.Threading.Lock.SourceGenerator`: a compile-time roslyn source code generator package that injects an `internal` `Lock` type to consumers of the library.

If you like this idea, I wouldn't mind having a go at it and creating a pull request for it in the next few days.

### PR DESCRIPTION
**Pull request by CptWesley**
Closes #1 

Note that the project files now contain quite some duplication. I personally prefer organizing things in dedicated `.props` files, but I did not want to mess with your setup right now.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
Thank you @CptWesley! I will try to review it today. It will take some time because I've never worked on source generators before. I will run some tests with it, like implementing it in a project and try breaking it :)

PS: do you not sleep?!

**Comment by MarkCiliaVincenti** [comment]
Also, not sure if this can be done or not, but would it be possible to have just one project which can be used either as is or as a source generator rather than 2 NuGet packages?

**Comment by CptWesley** [comment]
Haha, I like to get straight to programming the moment I wake up in the morning, hence my early contribution.

I'm not entirely sure if it's possible to keep it as a single assembly, but inside the nuget package it is included as an analyzer. That's what this bit takes care of:
```xml
<PropertyGroup>
  <IncludeSymbols>false</IncludeSymbols>
  <IncludeBuildOutput>false</IncludeBuildOutput>
</PropertyGroup>

<ItemGroup Label="DependencyPackaging">
  <None Include="$(OutputPath)/netstandard2.0/$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
</ItemGroup>
```

It ensures that the assembly itself is not included, but it copies the assembly over to the `analyzer/dotnet/cs` output directory, which ensures it is registered as a roslyn analyzer project (source code generators are technically roslyn analyzers). So perhaps it would be possible to pack both the regular `Backport.System.Threading.Lock` dll and the `Backport.System.Threading.Lock.SourceGenerator` as an analyzer in the same .nupkg file. Then you would just need some way to flag whether or not it should produce the source files.

You can retrieve some dependency information during the analyzer step from the compilation unit. Perhaps it is possible to find out if the package is included in the output. If it is not included, inject the source code, otherwise don't and just use the runtime dependency.

But this is also delving into code generator territory that I have not ventured into myself... 😅

**Comment by MarkCiliaVincenti** [comment]
Excellent @CptWesley, I will take a look as soon as I find some time.

In the meantime, do you know if it's possible to also ensure net9.0 is being targeted?
If it's a `<TargetFramework>net8.0</TargetFramework>` it would change it to `<TargetFramework**s**>net8.0;net9.0</TargetFramework**s**>` and `<TargetFramework**s**>netstandard2.0;net8.0</TargetFramework**s**>` would change it to `<TargetFramework**s**>netstandard2.0;net8.0;net9.0</TargetFramework**s**>`

**Comment by CptWesley** [comment]
@MarkCiliaVincenti I'm not entirely sure if I'm following what you are asking

**Comment by MarkCiliaVincenti** [comment]
> @MarkCiliaVincenti I'm not entirely sure if I'm following what you are asking

What I would like, if possible, that if a project that uses this source generator is not targeting net9, it modifies the source of that project forcing it to multi target net9.

**Comment by CptWesley** [comment]
@MarkCiliaVincenti I don't think that is possible with roslyn analyzers

**Comment by MarkCiliaVincenti** [comment]
This looks good to me! Just a small leftover reference to the project, but I'll fix that. Then the work on the documentation :) Thanks a lot for this @CptWesley! I'll make sure you're added to the contributors.

**Comment by MarkCiliaVincenti** [comment]
> Also, not sure if this can be done or not, but would it be possible to have just one project which can be used either as is or as a source generator rather than 2 NuGet packages?

I managed this @CptWesley :)

**Pull request merged**
